#!/usr/bin/env python3
"""
Configuration wizard for Flight Deal Bot
Helps users configure the bot interactively

IMPORTANT: Before running this, install requirements:
    pip install -r requirements.txt
    
Then run:
    python configure.py
"""

import os
import sys
from pathlib import Path

# Check if requirements are installed
try:
    import yaml
except ImportError:
    print("❌ Error: Required packages not installed!")
    print("\nPlease run first:")
    print("    pip install -r requirements.txt")
    print("\nThen run this script again.")
    sys.exit(1)

def print_header(text):
    """Print a header"""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")

def print_step(number, text):
    """Print a step"""
    print(f"\n{number}. {text}")
    print("-" * 60)

def get_input(prompt, default=None):
    """Get user input with optional default"""
    if default:
        response = input(f"{prompt} [{default}]: ").strip()
        return response if response else default
    return input(f"{prompt}: ").strip()

def main():
    """Interactive setup"""
    print_header("✈️ Flight Deal Bot - Setup Wizard")
    
    print("This wizard will help you configure your flight deal bot.")
    print("You can always edit config.yaml later to change settings.\n")
    
    # Check if config already exists
    if Path("config.yaml").exists():
        response = get_input("config.yaml already exists. Overwrite? (yes/no)", "no")
        if response.lower() not in ['yes', 'y']:
            print("Setup cancelled. Edit config.yaml manually if needed.")
            sys.exit(0)
    
    # Email configuration
    print_step(1, "Email Configuration")
    print("The bot will send deal alerts to your email via Gmail.")
    print("You'll need to create an App Password for Gmail.")
    print("Instructions: https://support.google.com/accounts/answer/185833\n")
    
    email_recipient = get_input("Your email address (where alerts will be sent)")
    gmail_sender = get_input("Gmail account for sending (can be same as above)", email_recipient)
    gmail_password = get_input("Gmail App Password (16 characters)")
    
    # API configuration
    print_step(2, "Amadeus API Configuration")
    print("Sign up for free at: https://developers.amadeus.com/")
    print("Free tier: 2000 API calls/month (enough for 4 checks/day)\n")
    
    amadeus_key = get_input("Amadeus API Key")
    amadeus_secret = get_input("Amadeus API Secret")
    
    # Route configuration
    print_step(3, "Flight Routes")
    print("Default: Warsaw (WAW) to São Paulo (GRU) and Rio (GIG)\n")
    
    origin = get_input("Origin airport code", "WAW")
    
    print("\nDestinations (Brazilian airports):")
    print("  GRU - São Paulo (Guarulhos)")
    print("  GIG - Rio de Janeiro")
    print("  BSB - Brasília")
    print("  SSA - Salvador")
    
    destinations_input = get_input("Destination codes (comma-separated)", "GRU,GIG")
    destinations = [d.strip().upper() for d in destinations_input.split(',')]
    
    # Trip preferences
    print_step(4, "Trip Preferences")
    
    trip_min = int(get_input("Minimum trip length (days)", "10"))
    trip_max = int(get_input("Maximum trip length (days)", "21"))
    
    flexible = get_input("Flexible duration? (yes/no)", "yes").lower() in ['yes', 'y']
    
    # Connection preferences
    print_step(5, "Connection Preferences")
    
    print("\nMaximum stops:")
    print("  0 - Direct flights only (rare, expensive)")
    print("  1 - One stop (most common)")
    print("  2 - Up to two stops (cheapest)")
    
    max_stops = int(get_input("Maximum stops", "1"))
    
    # Price thresholds
    print_step(6, "Price Thresholds (in PLN)")
    
    amazing_price = int(get_input("Amazing deal threshold", "2000"))
    great_price = int(get_input("Great deal threshold", "2500"))
    
    major_deal_percent = int(get_input("Major deal discount % (for alerts)", "20"))
    
    # Check frequency
    print_step(7, "Check Frequency")
    
    check_hours = int(get_input("Check every X hours (recommended: 6)", "6"))
    
    # Generate config
    print_step(8, "Generating Configuration")
    
    config_content = f"""# Flight Deal Bot Configuration
# Generated by setup wizard on {Path(__file__).stat().st_mtime}

email:
  recipient: "{email_recipient}"
  sender_gmail: "{gmail_sender}"
  smtp_password: "{gmail_password}"
  alert_frequency: "major_deals_only"
  major_deal_threshold_percent: {major_deal_percent}

api:
  amadeus_api_key: "{amadeus_key}"
  amadeus_api_secret: "{amadeus_secret}"

routes:
  origin: "{origin}"
  destinations:
{chr(10).join([f'    - "{dest}"' for dest in destinations])}

dates:
  search_window_days: 180
  departure_flexibility_days: 7
  trip_length:
    minimum_days: {trip_min}
    maximum_days: {trip_max}
    preferred_days: {(trip_min + trip_max) // 2}
    flexible_duration: {str(flexible).lower()}
  target_periods: []

connections:
  max_stops: {max_stops}
  min_layover_hours: 1.5
  max_layover_hours: 6.0
  preferred_hubs:
    - "FRA"
    - "AMS"
    - "MAD"
    - "LIS"
    - "IST"
  avoid_airlines: []
  allow_overnight_layover: false
  penalize_long_layovers: true
  penalize_airport_changes: true

airport_flexibility:
  different_return_airport: true
  max_ground_transport_cost: 200
  include_ground_transport_in_price: true
  warn_about_ground_transport: true

separate_tickets:
  enabled: true
  minimum_savings_percent: 20
  safe_self_transfer_hours: 4.0
  risk_tolerance: "moderate"
  show_risk_warnings: true

price_alerts:
  currency: "PLN"
  thresholds:
    amazing_deal: {amazing_price}
    great_deal: {great_price}
    good_deal: 3000
  percentage_thresholds:
    amazing_deal_percent: 25
    great_deal_percent: 20
    good_deal_percent: 15
  comparison_period_days: 30
  require_both_conditions: false

advanced:
  check_frequency_hours: {check_hours}
  keep_detailed_history_days: 30
  keep_aggregated_history_days: 365
  show_price_history_chart: false
  show_booking_links: true
  show_alternative_dates: true
  log_level: "INFO"
  send_error_notifications: true
  database_path: "data/flights.db"
"""
    
    # Write config
    with open("config.yaml", "w") as f:
        f.write(config_content)
    
    print("✅ Configuration saved to config.yaml")
    
    # Test email
    print_step(9, "Testing Email")
    
    test_email = get_input("Send test email? (yes/no)", "yes").lower() in ['yes', 'y']
    
    if test_email:
        print("\nTesting email configuration...")
        os.system("python main.py --test-email")
    
    # Final instructions
    print_header("Setup Complete!")
    
    print("Next steps:")
    print("  1. Review config.yaml and adjust if needed")
    print("  2. Test the bot: python main.py --once")
    print("  3. Deploy to cloud or run locally")
    print("\nQuick start commands:")
    print("  python main.py --test       # Dry run (no emails)")
    print("  python main.py --once       # Run once")
    print("  python main.py              # Run continuously")
    print("\nSee README.md for deployment instructions!")
    print("\n🎉 Happy deal hunting! ✈️🇧🇷\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
